Undo add and remove from reading list
rameshvemula-tmo/web-ui-developer-puzzle pull request #3
Opened 2020-08-17 21:41 UTC by rameshvemula

Tasks Completed: Added Undo functions in SnackBar Notification for both Add / Remove actions of Book list / Reading list.

![image](https://user-images.githubusercontent.com/2382045/90446942-dcfdc400-e0a7-11ea-8cf9-d193ef6235ad.png)

2020-08-18 01:31 UTC, jaysoo commented on apps/okreads-e2e/src/specs/reading-list.spec.ts
> +    const initialReadListCount = await browser.executeScript(`
You can just use `element.getText()` in protractor. And I would add the necessary `data-testing` attribute to any elements needed for testing.

For example,

```
const initialReadListCount = await $('[data-testing="total-count"]').getText()
```

The `executeScript` function is useful if you need to reach into exposed JS objects/functions in the browser, not really for selecting elements.

2020-08-18 01:32 UTC, jaysoo commented on apps/okreads-e2e/src/specs/reading-list.spec.ts
> +    browser.executeScript(`
Same here, I would use `data-testing` attribute, and you can use the normal protractor API for `.click()`.

2020-08-18 01:33 UTC, jaysoo commented on apps/okreads-e2e/src/specs/reading-list.spec.ts
> +    browser.executeScript(`
Can just use normal protractor API of `.click()` instead of `executeScript`.

2020-08-18 01:36 UTC, jaysoo commented on libs/books/feature/src/lib/book-search/book-search.component.ts
> +        this.store.dispatch(removeFromReadingList({ item: { bookId: id, ...bookremoved } }));
**Nitpick:** Use proper camelCase `bookRemoved`.

2020-08-18 01:39 UTC, jaysoo commented on libs/books/feature/src/lib/book-search/book-search.component.ts
> +    this.showSnackBarNotification(book);
An alternative way to show notification is to do this in the ngrx effects class.

There isn't a guarantee that dispatching `addToReadingList ` results in the book actually being removed, but the effect that handles this action will know whether it is resolved successfully or not.

2020-08-18 01:40 UTC, jaysoo commented on libs/books/feature/src/lib/reading-list/reading-list.component.ts
> +    this.showSnackBarNotification(item);
Same as previous comment on notification, the effects class would be more natural for this logic since it knows if and when the action is handled successfully.

2020-08-18 03:21 UTC, rameshvemula commented
@jaysoo  Totally agreed on usage of $ vs executeScript, updated the spec file where ever it can be used. 
While I was playing around to select snakbar notification element for which $ didn't work just fine due to timing issue I believe i ended up using executeScript for some of other selectors as well with out much thinking,, 

but yeah , for snakbar element I tried it to eliminate it with no luck, and just used executeScritpt to make use of document ...if you find the better way let me know.

code I have tried is:

browser.sleep(1000);
    ```
    const snackBar = element(by.tagName('simple-snack-bar'));
    await browser.wait(ExpectedConditions.visibilityOf(snackBar), 5000);
    const undoToAddBtn = await $('simple-snack-bar button') as HTMLButtonElement;
    undoToAddBtn.click();


```

2020-08-19 01:45 UTC, rameshvemula commented
@jaysoo  I moved Notification logic to effect as well, please review and let me know feedback !! thanks!

2020-08-25 09:33 UTC, jdpearce requested changes
Apart from the failing tests and the stray `debugger` statement, this looks mostly ok. I wouldn't worry too much about getting the tests to work in the ideal way, but if you *can* solve that problem...

Edit : Totally forgot to mention you need to squash your commits. Tidy them up and reduce to a single commit so that the history can be understood.

I'm also concerned that the first commit in this PR is a `merge` commit. This should be directly branched off the `chore/code-review` branch, so why is there a `merge` commit?

2020-08-25 09:33 UTC, jdpearce commented on libs/books/data-access/src/lib/+state/reading-list.effects.ts
> +          debugger;
You probably didn't mean to leave this in...?

2020-08-25 09:33 UTC, jdpearce commented on libs/books/data-access/src/lib/+state/reading-list.effects.ts
> +              SnackbarNotificationActions.snackbarOpen({
Just a thought - by putting the dispatch of these actions here rather than allowing snackbar effects to fire from ReadingListActions you're making this set of effects entirely responsible for showing/hiding the snackbar when this isn't necessarily a concern that it should have.

You could probably do away with the snackbar actions entirely and just trigger the effects on ReadingListActions.

2020-08-25 09:33 UTC, jdpearce commented on libs/books/data-access/src/lib/+state/reading-list.effects.ts
> +              SnackbarNotificationActions.snackbarOpen({
If you did want to make it explicit with snackbar actions, you could always create mapping effects which map a ReadingListAction directly to a SnackBarNotificationAction.

Not necessary to change, but just a thought.

2020-08-25 09:33 UTC, jdpearce commented on apps/okreads-e2e/src/specs/reading-list.spec.ts
> +    browser.executeScript(`
Except it doesn't work.

I can't get this to work either way round tbh. 

These tests fail for me done either way. I'm not going to consider these as a crucial part of the test since getting them to work appears to be more a matter of magic than ability.

2020-08-25 09:33 UTC, jdpearce commented on libs/books/data-access/src/lib/+state/snackbar-notification.actions.ts
> +    notifType?: string,
Not a fan of abbeviating variables like this. We've got space. Call it `notificationType`

2020-08-25 09:33 UTC, jdpearce commented on libs/books/data-access/src/lib/+state/snackbar-notification.effects.ts
> +                  if ( notifType === SNACKBAR_CONFIG_CONSTANT.ITEM_REMOVE) {
Let's assume there might be more types in the future...why not use a switch statement?

2020-08-25 09:33 UTC, jdpearce commented on libs/books/feature/src/lib/snackbar-config.constants.ts
> +}
This should be a linting error?

2020-08-25 09:33 UTC, jdpearce commented on apps/okreads-e2e/src/specs/reading-list.spec.ts
> +    browser.executeScript(`
How would you add a `data-testing` attribute to the `mat-snackbar` component? 🤔

2020-08-25 14:47 UTC, closed without merging

2020-08-25 15:12 UTC, rameshvemula commented
closed this MR and opened new one with same changes. https://github.com/rameshvemula-tmo/web-ui-developer-puzzle/pull/5